# Generated by Django 2.2.1 on 2019-05-21 07:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('reportada', '0002_auto_20190514_1138'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cards',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=16)),
                ('ccv', models.CharField(max_length=4)),
            ],
        ),
        migrations.CreateModel(
            name='Clientes',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pago_por_defecto', models.CharField(choices=[('Efectivo', 'Efectivo'), ('Paypal', 'Paypal'), ('Tarjeta de Credito/Debito', 'Tarjeta de Credito/Debito')], max_length=25)),
                ('paypal', models.EmailField(blank=True, max_length=64)),
            ],
        ),
        migrations.CreateModel(
            name='Direcciones',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre_calle', models.CharField(max_length=40)),
                ('tipo_calle', models.CharField(max_length=20)),
                ('num_casa', models.CharField(blank=True, max_length=6)),
                ('colonia', models.CharField(max_length=40)),
                ('codigo_postal', models.CharField(max_length=6)),
                ('ciudad', models.CharField(max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Empleados',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('curp', models.CharField(max_length=18)),
                ('rfc', models.CharField(max_length=13)),
                ('nss', models.CharField(max_length=11)),
                ('sexo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='Productos',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descripcion', models.CharField(max_length=128)),
                ('precio', models.FloatField()),
                ('size', models.CharField(blank=True, choices=[('Individual', 'Individual'), ('Mediana', 'Mediana'), ('Grande', 'Grande'), ('Familiar', 'Familiar')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Usuarios',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('middle_name', models.CharField(blank=True, max_length=150)),
                ('fecha_nacimiento', models.DateField(blank=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Ventas',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estatus', models.CharField(choices=[('Pendiente', 'Pendiente'), ('Cancelada', 'Cancelada'), ('Finalizada', 'Finalizada')], max_length=10)),
                ('fecha', models.DateTimeField(auto_now_add=True)),
                ('impuesto', models.FloatField()),
                ('subtotal', models.FloatField()),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Clientes')),
            ],
        ),
        migrations.CreateModel(
            name='VentasDetalle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.IntegerField()),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Productos')),
                ('venta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Ventas')),
            ],
        ),
        migrations.DeleteModel(
            name='Cliente',
        ),
        migrations.AddField(
            model_name='ventas',
            name='productos',
            field=models.ManyToManyField(through='reportada.VentasDetalle', to='reportada.Productos'),
        ),
        migrations.AddField(
            model_name='empleados',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Usuarios'),
        ),
        migrations.AddField(
            model_name='direcciones',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Usuarios'),
        ),
        migrations.AddField(
            model_name='clientes',
            name='usuario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Usuarios'),
        ),
        migrations.AddField(
            model_name='cards',
            name='cliente',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='reportada.Clientes'),
        ),
    ]
